plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.3.3.cjs

packageExtensions:
  # Fix for graphql-api codegen
  '@graphql-tools/code-file-loader@*':
    dependencies:
      'ts-node': '*'
  'apollo-link@*':
    dependencies:
      'graphql': '*'
  'apollo-link-http@*':
    dependencies:
      'graphql': '*'
  'apollo-upload-client@*':
    dependencies:
      'graphql': '*'
