packageExtensions:
  '@graphql-modules/di@*':
    dependencies:
      reflect-metadata: '*'
  '@graphql-tools/code-file-loader@*':
    dependencies:
      ts-node: '*'
  apollo-link-http@*:
    dependencies:
      graphql: '*'
  apollo-link@*:
    dependencies:
      graphql: '*'
  apollo-upload-client@*:
    dependencies:
      graphql: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
